name: Publication automatique du site sur GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-pages:
    runs-on: ubuntu-lasted

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Recuperation du projet
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparation de l'artefact du site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploiement du site sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

